import type { Metadata } from "next";
import Navbar from "../../components/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "dohyun's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
